{% set name = "dxtb" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dxtb-{{ version }}.tar.gz
  sha256: f578b2fb9b9ded19c10770ac9c386d5c3afef79f5c3bc403464e99b708d8fff8

build:
  entry_points:
    - dxtb = dxtb._src.cli:console_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - setuptools
    - pip
  run:
    - python >=3.8,<3.12
    - numpy <2
    - pydantic >=2.0.0
    - scipy
    - tad-dftd3 >=0.3.0
    - tad-dftd4 >=0.2.0
    - tad-mctc >=0.2.0
    - tad-multicharge
    - tomli
    - tomli-w
    - pytorch >=1.11.0,<2.4
    - typing-extensions

test:
  imports:
    - dxtb
  commands:
    - pip check
    - dxtb --version
  requires:
    - pip

about:
  summary: Fully Differentiable Approach to Extended Tight Binding
  home: https://github.com/grimme-lab/dxtb
  dev_url: https://github.com/grimme-lab/dxtb
  doc_url: https://dxtb.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
