{% set name = "dxtb" %}
{% set version = "0.3.0" %}
{% set python_min = "3.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dxtb-{{ version }}.tar.gz
  sha256: ca163510e132bde6d4c701b9b611a559f8d59ccbb94ca2dd98571769128cdcc8

build:
  entry_points:
    - dxtb = dxtb._src.cli:console_entry_point
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }},<3.13
    - numpy <2
    - pydantic >=2.0.0
    - scipy
    - tad-dftd3 >=0.3.0
    - tad-dftd4 >=0.2.0
    - tad-mctc >=0.2.0
    - tad-multicharge
    - tomli
    - tomli-w
    - pytorch >=1.11.0,<2.5
    - typing-extensions

test:
  imports:
    - dxtb
  commands:
    - pip check
    - dxtb --version
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Fully Differentiable Approach to Extended Tight Binding
  home: https://github.com/grimme-lab/dxtb
  dev_url: https://github.com/grimme-lab/dxtb
  doc_url: https://dxtb.readthedocs.io/
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marvinfriede
